# Specifies the AWS CloudFormation template format version
AWSTemplateFormatVersion: '2010-09-09'

# Applies AWS SAM transform to simplify serverless syntax
Transform: AWS::Serverless-2016-10-31

# Description of the SAM application
Description: SNS Demo with SAM and Python

# Set global defaults for all AWS::Serverless::Function resources
Globals:
  Function:
    Timeout: 10              # Set timeout to 10 seconds for all Lambda functions
    Runtime: python3.12      # Set Python runtime globally

Resources:

  # This is the Lambda function that publishes messages to the SNS topic
  SnsPublishFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SNS-DEMO            # Custom name for the Lambda function
      Handler: app.lambda_handler       # Entry point in app.py (function: lambda_handler)
      CodeUri: hello_world/             # Directory containing Lambda source code
      Events:
        ApiTrigger:
          Type: Api                     # Trigger type is API Gateway (REST API)
          Properties:
            Path: /publish              # API endpoint path
            Method: post                # HTTP method
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref MySNSTopic  # Pass SNS topic ARN as an environment variable
      Policies:
        - Statement:
            - Effect: Allow
              Action: sns:Publish       # Grant Lambda permission to publish to SNS
              Resource: !Ref MySNSTopic # The specific SNS topic it can publish to

  # This defines the SNS topic that will receive messages from the Lambda function
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: SNS DEMO             # Human-readable name (used in emails, etc.)
      TopicName: SNS-DEMO               # Custom topic name (instead of autogenerated one)

Outputs:
  # Outputs section displays the deployed API URL in the terminal after deployment
  ApiUrl:
    Description: "API Gateway endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/publish"
    # Substitutes region and API Gateway ID into the final API URL
